import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const dir = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(dir, "pkg", "ironmark_bg.wasm");
const outPath = join(dir, "node.js");

const wasmBase64 = readFileSync(wasmPath).toString("base64");

const source = `// Generated by wasm/build.mjs — do not edit
import * as wasmGlue from "./pkg/ironmark_bg.js";
import { createParse } from "./shared.js";

const wasmBytes = Uint8Array.from(atob(${JSON.stringify(wasmBase64)}), (c) => c.charCodeAt(0));
const wasmModule = new WebAssembly.Module(wasmBytes);
const wasmInstance = new WebAssembly.Instance(wasmModule, { "./ironmark_bg.js": wasmGlue });

wasmGlue.__wbg_set_wasm(wasmInstance.exports);

export function init() {}

export const parse = createParse(wasmGlue.parse);
`;

writeFileSync(outPath, source);
console.log(`Generated ${outPath} (${(wasmBase64.length / 1024).toFixed(1)} KiB base64)`);
